from yacs.config import CfgNode


_C = CfgNode()

# Train Params
_C.TRAIN = CfgNode()
_C.TRAIN.ADD_KNN = True
_C.TRAIN.BATCH_SIZE = 256
_C.TRAIN.EASY_MARGIN = True
_C.TRAIN.LEARNING_RATE = 1e-4
_C.TRAIN.MARGIN = 0.5
_C.TRAIN.MODEL_TYPE = ''
_C.TRAIN.MOMENTUM = 0.9
_C.TRAIN.NUM_EPOCHS = 1
_C.TRAIN.NUM_GPUS = 1
_C.TRAIN.OPTIMIZER_TYPE = ''
_C.TRAIN.RUN_NAME = ''
_C.TRAIN.SCALE_FACTOR = 30.0
_C.TRAIN.SEED = 42
_C.TRAIN.WEIGHT_PATH = ''

_C.DATA = CfgNode()
_C.DATA.CLASS_LIST = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
_C.DATA.IMG_SIZE = (32, 32)
_C.DATA.ROOT_PATH = './dataset'
_C.DATA.TRANSFORM_LIST = ['resize', 'horizontal_flip', 'to_tensor']
_C.DATA.TRAIN_SIZE_RATE = 0.8
_C.DATA.NUM_WORKERS = 32
